sudo: false
language: go

go:
  - 1.11.x
  - master

# Only clone the most recent commit.
git:
  depth: 1

matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go build outbound-link-checker.go
  - go tool vet .
  # We don't have tests yet
#  - go test -v -race ./...
