---
name: Lint and test Go

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Format
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: Build
        run: make build_debug

        # We don't have tests yet
        # go test -v ./...
      - name: Vet
        run: make test
