name: Go

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.23"

# Not needed
#     - name: Fetch
#       run: go get -t -v ./...
      
    - name: Format
      run: diff -u <(echo -n) <(gofmt -d -s .)
    
    - name: Build
      run: make build
      
      # We don't have tests yet
      # go test -v ./...  
    - name: Vet
      run: make lint
